// AUTO-GENERATED list of bundled seed media requires (Metro needs static require paths).
// Arrays are index-aligned where relevant (POST_ASSETS[i] <-> POST_THUMB_ASSETS[i], REEL_VIDEO_ASSETS[i] <-> REEL_THUMB_ASSETS[i]).

export const AVATAR_ASSETS = [
  require('../../assets/seed/avatar_0.jpg'),
  require('../../assets/seed/avatar_1.jpg'),
  require('../../assets/seed/avatar_2.jpg'),
  require('../../assets/seed/avatar_3.jpg'),
  require('../../assets/seed/avatar_4.jpg'),
  require('../../assets/seed/avatar_5.jpg'),
  require('../../assets/seed/avatar_6.jpg'),
  require('../../assets/seed/avatar_7.jpg'),
  require('../../assets/seed/avatar_8.jpg'),
  require('../../assets/seed/avatar_9.jpg'),
  require('../../assets/seed/avatar_10.jpg'),
  require('../../assets/seed/avatar_11.jpg'),
];

export const POST_ASSETS = [
  require('../../assets/seed/post_0.jpg'),
  require('../../assets/seed/post_1.jpg'),
  require('../../assets/seed/post_2.jpg'),
  require('../../assets/seed/post_3.jpg'),
  require('../../assets/seed/post_4.jpg'),
  require('../../assets/seed/post_5.jpg'),
  require('../../assets/seed/post_6.jpg'),
  require('../../assets/seed/post_7.jpg'),
  require('../../assets/seed/post_8.jpg'),
  require('../../assets/seed/post_9.jpg'),
  require('../../assets/seed/post_10.jpg'),
  require('../../assets/seed/post_11.jpg'),
  require('../../assets/seed/post_12.jpg'),
  require('../../assets/seed/post_13.jpg'),
  require('../../assets/seed/post_14.jpg'),
  require('../../assets/seed/post_15.jpg'),
  require('../../assets/seed/post_16.jpg'),
  require('../../assets/seed/post_17.jpg'),
  require('../../assets/seed/post_18.jpg'),
  require('../../assets/seed/post_19.jpg'),
  require('../../assets/seed/post_20.jpg'),
  require('../../assets/seed/post_21.jpg'),
  require('../../assets/seed/post_22.jpg'),
  require('../../assets/seed/post_23.jpg'),
];

export const POST_THUMB_ASSETS = [
  require('../../assets/seed/post_0_thumb.jpg'),
  require('../../assets/seed/post_1_thumb.jpg'),
  require('../../assets/seed/post_2_thumb.jpg'),
  require('../../assets/seed/post_3_thumb.jpg'),
  require('../../assets/seed/post_4_thumb.jpg'),
  require('../../assets/seed/post_5_thumb.jpg'),
  require('../../assets/seed/post_6_thumb.jpg'),
  require('../../assets/seed/post_7_thumb.jpg'),
  require('../../assets/seed/post_8_thumb.jpg'),
  require('../../assets/seed/post_9_thumb.jpg'),
  require('../../assets/seed/post_10_thumb.jpg'),
  require('../../assets/seed/post_11_thumb.jpg'),
  require('../../assets/seed/post_12_thumb.jpg'),
  require('../../assets/seed/post_13_thumb.jpg'),
  require('../../assets/seed/post_14_thumb.jpg'),
  require('../../assets/seed/post_15_thumb.jpg'),
  require('../../assets/seed/post_16_thumb.jpg'),
  require('../../assets/seed/post_17_thumb.jpg'),
  require('../../assets/seed/post_18_thumb.jpg'),
  require('../../assets/seed/post_19_thumb.jpg'),
  require('../../assets/seed/post_20_thumb.jpg'),
  require('../../assets/seed/post_21_thumb.jpg'),
  require('../../assets/seed/post_22_thumb.jpg'),
  require('../../assets/seed/post_23_thumb.jpg'),
];

export const STORY_ASSETS = [
  require('../../assets/seed/story_0.jpg'),
  require('../../assets/seed/story_1.jpg'),
  require('../../assets/seed/story_2.jpg'),
  require('../../assets/seed/story_3.jpg'),
  require('../../assets/seed/story_4.jpg'),
  require('../../assets/seed/story_5.jpg'),
  require('../../assets/seed/story_6.jpg'),
  require('../../assets/seed/story_7.jpg'),
  require('../../assets/seed/story_8.jpg'),
  require('../../assets/seed/story_9.jpg'),
  require('../../assets/seed/story_10.jpg'),
  require('../../assets/seed/story_11.jpg'),
];

export const REEL_THUMB_ASSETS = [
  require('../../assets/seed/reel_thumb_0.jpg'),
  require('../../assets/seed/reel_thumb_1.jpg'),
  require('../../assets/seed/reel_thumb_2.jpg'),
  require('../../assets/seed/reel_thumb_3.jpg'),
  require('../../assets/seed/reel_thumb_4.jpg'),
  require('../../assets/seed/reel_thumb_5.jpg'),
  require('../../assets/seed/reel_thumb_6.jpg'),
  require('../../assets/seed/reel_thumb_7.jpg'),
  require('../../assets/seed/reel_thumb_8.jpg'),
  require('../../assets/seed/reel_thumb_9.jpg'),
];

export const REEL_VIDEO_ASSETS = [
  require('../../assets/seed/reel_0.mp4'),
  require('../../assets/seed/reel_1.mp4'),
  require('../../assets/seed/reel_2.mp4'),
  require('../../assets/seed/reel_3.mp4'),
  require('../../assets/seed/reel_4.mp4'),
];
